# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kharch', '0006_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='form',
            field=models.CharField(choices=[(b'ELEC', b'Electronic'), (b'CASH', b'Cash')], default=b'CASH', max_length=4),
        ),
    ]
